#!/bin/sh

set -e

cd "$1"

exec 3>&1
exec 1>&2

PAYLOAD=$(mktemp /tmp/resource-put.XXXXXX)

cat >"$PAYLOAD" <&0



debug=$(jq -r '.source.debug // false' <"$PAYLOAD")
[ "$debug" = "true" ] && set -x

server="$(jq -r '.source.server // empty' <"$PAYLOAD")"
[ "$debug" = "true" ] && set +x
username="$(jq -r '.source.username // empty' <"$PAYLOAD")"
password="$(jq -r '.source.password // empty' <"$PAYLOAD")"
[ "$debug" = "true" ] && set -x

recipients="$(jq -r '.source.recipients | .[]? // empty' <"$PAYLOAD")"
rooms="$(jq -r '.source.rooms | .[]? // empty' <"$PAYLOAD")"

room_nick="$(jq -r '.source.room_nick // "concourse"' <"$PAYLOAD")"
skip_ssl_verification="$(jq -r '.source.skip_ssl_verification // "false"' <"$PAYLOAD")"
disable_ssl="$(jq -r '.source.disable_ssl // "false"' <"$PAYLOAD")"
ca_cert=$(jq -r '.source.ca_cert // empty' <"$PAYLOAD")

message="$(jq -r '.params.message // empty' <"$PAYLOAD")"
message_file="$(jq -r '.params.message_file // empty' <"$PAYLOAD")"


: "${server:?Missing required option: \"server\"}"
[ "$debug" = "true" ] && set +x
: "${username:?Missing required option: \"username\"}"
: "${password:?Missing required option: \"password\"}"
[ "$debug" = "true" ] && set -x

if [ -z "$rooms" ] && [ -z "$recipients" ]; then
    echo "Missing required option: \"rooms\" or \"recipients\""
    exit 1
fi

if [ -z "$message" ] && [ -z "$message_file" ]; then
    echo "Missing required parameter: \"message\" or \"message_file\""
    exit 1
fi

if [ -n "$message" ] && [ -n "$message_file" ]; then
    echo "Only one parameter must be specified: \"message\" or \"message_file\""
    exit 1
fi


SENDXMPP_OPTS=""
SENDXMPP_RECIPIENTS=""

if [ -n "$ca_cert" ]; then
    cert_dir=$(mktemp -d /tmp/resource-cert.XXXXXX)
    echo "$ca_cert" >"$cert_dir/$server.crt"
    SENDXMPP_OPTS="$SENDXMPP_OPTS --tls-ca-path $cert_dir/$server.crt"
else
    # TODO See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854210
    SENDXMPP_OPTS="$SENDXMPP_OPTS --tls-ca-path /etc/ssl/certs"
fi

if [ "$skip_ssl_verification" = "true" ]; then
    SENDXMPP_OPTS="$SENDXMPP_OPTS --no-tls-verify"
fi

if [ "$disable_ssl" = "false" ]; then
    SENDXMPP_OPTS="$SENDXMPP_OPTS --tls"
fi

if [ "$debug" = "true" ]; then
    SENDXMPP_OPTS="$SENDXMPP_OPTS --verbose"
fi

if [ -n "$recipients" ]; then
    SENDXMPP_RECIPIENTS="$recipients"
fi

if [ -n "$rooms" ]; then
    SENDXMPP_RECIPIENTS="--resource $room_nick --chatroom $rooms"
fi

if [ -n "$message_file" ]; then
    if [ -f "$message_file" ]; then
        message="$(cat "$message_file")"
    else
        echo "$message_file file not found"
        exit 1
    fi
fi

if [ -z "$message" ]; then
    echo "No message provided. Exiting."
    jq -n "{ version: { timestamp: \"$(date +%s)\" } }" >&3
    exit 0
fi


message="$(echo "$message" | envsubst)"
message_file_tmp=$(mktemp /tmp/resource-msg.XXXXXX)
clean_tmp_files() {
  rm -rf "$message_file_tmp"
}
trap clean_tmp_files EXIT
echo "$message" >"$message_file_tmp"


[ "$debug" = "true" ] && set +x
# shellcheck disable=SC2086
sendxmpp $SENDXMPP_OPTS -j "$server" -u "$username" -p "$password" \
    -m "$message_file_tmp" $SENDXMPP_RECIPIENTS
[ "$debug" = "true" ] && set -x


jq -n "{ version: { timestamp: \"$(date +%s)\" } }" >&3
